### ISSUE TITLE
woocommerce coupon text margin undefined

### ISSUE THREAD

**Issue by djcowan** [craftwerkberlin/bootscore-5#1]
https://github.com/craftwerkberlin/bootscore-5/blob/c806c4f1f87481b34df6d74ec40a3dcd986db713/woocommerce/css/woocommerce.css#L53

`#add_payment_method table.cart td.actions .coupon .input-text,
.woocommerce-cart table.cart td.actions .coupon .input-text,
.woocommerce-checkout table.cart td.actions .coupon .input-text {
margin: 
}`

**Comment by craftwerkberlin** [comment]
Has been fixed in 5.0.0.3. 

Thnx djcowan
