### ISSUE TITLE
masonry not included in js?

### ISSUE THREAD

**Issue by matthijsbro** [craftwerkberlin/bootscore-5#2]
I could activate the masonry style category, but had to add the javascript myself, is it no longer included in the theme?

**Comment by craftwerkberlin** [comment]
Hello matthijsbro,

yes. thats confusing. Bootstrap 5 does not have masonry anymore, instead they provided an example using masonry.js. So, I made a plugin that registers masonry, you can download it here https://github.com/craftwerkberlin/bs5-masonry.

However, on the demosite https://bootscore.me/category/archives/masonry/ is that plugin not installed, but it seems to work without plugin on my devices. So i cannot say what Bootstrap actually made in its JavaScript. Is that plugin needed or not? Can you sent a screenshot from your masonry site without your JavaScript and without the plugin? That would be very helpful.

**Comment by matthijsbro** [comment]
Ah, super, now I get it. May just register it myself in child-theme too I guess.

**Comment by craftwerkberlin** [comment]
Good. But much more important: What happens if you deactivate the plugin? Does the demosite https://bootscore.me/category/archives/masonry/ look well or are there any issuses in your browser? I need to figure out if that plugin is mandatory to display correctly or not.

Thank you

**Comment by matthijsbro** [comment]
That page looks totally fine. If the masonry javascript isn't there it just puts everything as if 'category-equal-height' but not with equal height. Which only starts to look terrible when there is very unequal heights.

**Comment by craftwerkberlin** [comment]
Can you make a screenshot from https://bootscore.me/category/archives/masonry/ please? And which OS and Browser do you use?

**Comment by matthijsbro** [comment]
I'm on a Macbook Firefox 86. Safari looks the same too. 
<img width="1241" alt="Screenshot 2021-03-07 at 16 13 05" src="https://user-images.githubusercontent.com/803217/110244673-191f4600-7f60-11eb-8765-d0901784bbd9.png">

**Comment by craftwerkberlin** [comment]
Ok, that page is without the plugin and seems to work fine. Means thet plugin is not needed. But than i do not understand why you open the issue?

**Comment by matthijsbro** [comment]
I'm sorry if we misunderstand each other or if I opened this issue for something that can't be resproduced. What I did: 
I dowloaded you theme + childtheme, copied category-masonry.php to category.php, and it didn't quite work. It showed the cards in unequal heights, but they didn't 'fit' as nice and snug . I did the same with your bootscore4 and it did work as supposed. I then added that masonry javascript from masonry.desandro.com to my boostscore 5 template file and it did work correctly. I reported here with my issue/question. 

I may have made a mistake somewhere, in which case I'm sorry to have bothered you. Although it seems quite straight forward to me and I'd have no idea what to alter to make it work without the masonry.js

**Comment by craftwerkberlin** [comment]
Hey matthijsbro,

you did not make any mistake. What you wrote is very important. I have to figure out is if masonry.js is needed or not. So, can you please remove your masonry.js and the plugin i provided above and check if the category is displayed correctly and make a screenshot?

As described above, in my site it works without masonry.js, but Bootstrap says masonry neccessary, this is very confusing and I need help from users to figure that out.

Thnx for reporting

**Comment by matthijsbro** [comment]
So here are two screenshots from the site I'm working on. The site is a (very) old Wordpress site, but updated to wp5.6.2 so that shouldn't be an issue. You can see the difference with and without the js. I changed stuff of course, so I also add my category.php. 
`
<?php
	/**
	 * Category Template: Masonry
	 *
	 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/
	 *
	 * @package Bootscore
	 */
	
	get_header();
	?>
     
<div id="content" class="site-content container py-5 mt-5">
    <div id="primary" class="content-area">

        
        <?php bs_after_primary(); ?>    

    <div class="row">
    <div class="col">

        <main id="main" class="site-main">

            <header class="page-header mb-4">
                <h1><?php single_cat_title(); ?></h1>
                <?php the_archive_description( '<div class="archive-description">', '</div>' ); ?>
            </header>

            <div class="row" data-masonry='{"percentPosition": true }'>
                <?php if (have_posts() ) : ?>
                <?php while (have_posts() ) : the_post(); ?>

                <div class="col-md-6 col-lg-4 mb-4">

                    <div class="card">
                        <h2 class="blog-post-title">
                            <a href="<?php the_permalink(); ?>">
                                <?php the_title(); ?>
                            </a>
                        </h2>

                        <?php if ( 'post' === get_post_type() ) : ?>
                        <small class="text-muted mb-2">
                            <?php
                            the_date();
                            ?>
                        </small>
                        <?php endif; ?>

                        <?php the_post_thumbnail('medium', array('class' => 'card-img')); ?>

                        <div class="card-body">

                            <div class="card-text">
                                <?php the_excerpt(); ?>
                            </div>

                            <div class="">
                                <a class="read-more" href="<?php the_permalink(); ?>"><?php _e('Read more »', 'bootscore'); ?></a>
                            </div>

                        </div>

                    </div>

                </div>

                <?php endwhile; ?>
                <?php endif; ?>

            </div>

            
            <div>
                <?php bootscore_pagination(); ?>
            </div>

        </main>
    </div>
    <?php get_sidebar(); ?>
    </div>
</div>
<?php
get_footer();

`



<img width="1008" alt="Screenshot 2021-03-08 at 11 24 59" src="https://user-images.githubusercontent.com/803217/110309198-55ef4980-8001-11eb-834a-42ec13f26550.png">
<img width="1001" alt="Screenshot 2021-03-08 at 11 23 31" src="https://user-images.githubusercontent.com/803217/110309205-57207680-8001-11eb-9480-4f39bf44c52a.png">

**Comment by matthijsbro** [comment]
At the risk of stupid questions... Perhaps your masonry.js packed with another js at some time? Or cached?

**Comment by craftwerkberlin** [comment]
Ah, question is answered, thank you very much ;-)

masonry.js is needed, I will publish the plugin in the shop and update documentation soon.

For the 2nd question, my cache is always disabled when developing and its not packed with another js file. Its mystery why this happen. 

Thanx for reporting and helping, will close this issue now.
