### ISSUE TITLE
Any chance of a version for devs along the lines of Understrap?

### ISSUE THREAD

**Issue by mattneal-stafflink** [craftwerkberlin/bootscore-5#3]
See title?

I think it would be good to be able to customise the Bootstrap CSS, and potentially bundle up Gulp for Sass etc?

**Comment by craftwerkberlin** [comment]
Hi,

yes, I see title. bootScore uses the compiled bootstrap.min.css. So you must download source code and compile min.css by yourself and replace it in theme. At the moment, there is no plan to integrate Sass in theme. But it can be a feature in later releases.

However, I am not a specialist with this tools. If you have time and knowledge to integrate that in the theme, you are welcome to contribute.

**Comment by craftwerkberlin** [comment]
Customizing the Bootstrap will not take place inside the theme. I created a simple Sass template for Visual Studio Code where you can edit and compile Bootstrap and use it in bootScore theme. https://github.com/craftwerkberlin/bootstrap-5-sass-template-for-vscode
