### ISSUE TITLE
Issue with 2FA plugin (WooCommerce - form-login.php)

### ISSUE THREAD

**Issue by cemmos** [craftwerkberlin/bootscore-5#5]
I'm technically using the bootCommerce 5 Child Theme, but the child theme doesn't replace the form-login.php file, so I figured this would be the best place to post about this issue.

After trying to figure out what the issue was, I discovered that the form-login.php file is the issue with trying to log in with the [Two Factor Authentication](https://wordpress.org/plugins/two-factor-authentication/) plugin. The 2FA works using the default Twenty Twenty-One theme as well as the Storefront theme from WooCommerce (as well as other themes, but those are the ones I've tried personally).

**What's supposed to happen:**
When you try to log in after entering your username and password and pressing enter or clicking the login button, the 2FA plugin then inserts an input where you type in your 2FA code. It does this by using jQuery, I believe.

**What happens with this theme:**
When using bootScore-5/bootCommerce, the 2FA plug is unable to insert the input — there seems to be a page load after hitting the login button, and the error "_The one-time password (TFA code) you entered was incorrect_" pops up since you're unable to enter the 2FA code. When I remove the `bootscore-5/woocommerce/myaccount/form-login.php` file and try again, the 2FA process works as it should.

I imagine it wouldn't just be that plugin alone that would break, so fixing the issue would likely be better for overall compatibility with other 3rd party plugins.

**Comment by craftwerkberlin** [comment]
Hello Cemmos,

thank you for reporting, I will check that.

1. Do you use the offcanvas login or a page for login?

2. Have a link to your site to check and understand that issue?

Basti

**Comment by Cemmos** [comment]
Hey, Basti. I tried both the offcanvas and the regular page, the issue appears on both. I just now set up a test site here after seeing your reply: [wp.dev.obstance.com](https://wp.dev.obstance.com/)

2FA can be turned on directly from the My Account page. You can either register a new user or use this test user that I set up and then turn on 2FA, then log out and try logging back in:

Username: testuser
Password: m1%b4Hq5ce5t

**Comment by craftwerkberlin** [comment]
Hey Cemmos,

I see… It seems there is a missing hook in form-login.php. Can you please rename or delete this file in theme that I can check that?

Thank you

Basti

**Comment by Cemmos** [comment]
Thanks, Basti. I've now removed the file.

**Comment by craftwerkberlin** [comment]
Hello cemmos,

The Two Factor Authentication plugin needs premium subscription to implement it in WooCommerce, so I cannot check it here on my site. 

But I created a new form-login.php [https://github.com/craftwerkberlin/woocommerce-form-login/blob/main/form-login.php](https://github.com/craftwerkberlin/woocommerce-form-login/blob/main/form-login.php)

Please replace existing one with this and give a feedback if it works.

Best regards Basti

**Comment by craftwerkberlin** [comment]
Hi cemmos,

it works now, pls check: https://wp.dev.obstance.com/my-account

But it works not in offcanvas. So, you must use static page if you want to use the plugin. I removed the offcanvas in header.php in child and hard coded the link to the account page there. If you click the user button, you will be directed to the account page.

If that's fine I will close this issue now?

**Comment by cemmos** [comment]
Indeed it does work! Thanks for your time with this issue, Basti. Much appreciated.

**Comment by craftwerkberlin** [comment]
Hi cemmos,

can you please send me the parent theme as zip back to store at bootscore.me? Unfortunately I deleted the wrong file ;-)

Thank you
