### ISSUE TITLE
Offcanvas 'Remember me' conflicting with form-login.php

### ISSUE THREAD

**Issue by cemmos** [craftwerkberlin/bootscore-5#8]
Just a small issue I noticed. Since the offcanvas login form and WooCommerce myaccount/form-login.php have the same IDs, we get invalid HTML markup. As well, the remember me checkbox can't be checked by clicking on the "Remember me" label because of the duplicate IDs (it works in the offcanvas form, but not on the my-account login form).

This can be seen on the official bootScore website while logged out: https://bootscore.me/account/

![id-conflict](https://user-images.githubusercontent.com/5217755/127862186-e3dd8bbf-e716-4e15-b7f7-673076a89046.png)

**Comment by craftwerkberlin** [comment]
This will be fixed in the next release.

**Comment by craftwerkberlin** [comment]
Fixed in 5.0.2.4
